# permissions for end users to view uptimetests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uptimetest-viewer-role
rules:
- apiGroups:
  -.sre.mls.io
  resources:
  - uptimetests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  -.sre.mls.io
  resources:
  - uptimetests/status
  verbs:
  - get
